name: Weekly UFC Scraper

on:
  schedule:
    - cron: '0 3 * * 1'  # every Monday at 3 AM UTC
  workflow_dispatch:  # allow manual trigger

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt || true  # or manually list: pip install pandas requests beautifulsoup4 openpyxl

    - name: Run UFC scraper
      run: python ufcdata.py

    - name: Commit updated files
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add -A
        git commit -m "Auto-update UFC dataset on schedule" || echo "No changes to commit"
        git push
